{
  "openapi": "3.0.0",
  "info": {
    "title": "Vehicle Service Reservation API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://{{baseurl}}"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "paths": {
    "/api/auth/login": {
      "post": {
        "tags": ["Vehicle Service Reservation API"],
        "summary": "Login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": "{\n    \"username\" : \"dealertest\",\n    ads213\n}"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "225"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"e1-KbNEx3/5J5Abmcav/XmTZqJjrWw\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 21 Jan 2026 17:35:23 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": true,\n    \"data\": {\n        \"token\": \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGVhbGVyIFRlc3QiLCJhZGRyZXNzIjoiQWRkcmVzcyBUZXN0IiwiaWF0IjoxNzY5MDE2OTIzLCJleHAiOjE3NjkwMjA1MjN9.ZxY1o93_ELN5e1_FFI9g0O7in7j0Sc7Df9qoxczuJu0\"\n    }\n}"
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "106"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"6a-LiBcYowYV4I1w/kl960MuuS05og\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 21 Jan 2026 17:38:34 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": false,\n    \"message\": \"AUTHENTICATION_ERROR\",\n    \"errors\": {\n        \"credentials\": [\n            \"Username or password wrong\"\n        ]\n    }\n}"
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "93"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"5d-S3pW5zUFrN0vN8vLsXR7sxUoQgE\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 21 Jan 2026 17:37:34 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": false,\n    \"message\": \"VALIDATION_ERROR\",\n    \"errors\": {\n        \"password\": [\n            \"password is required\"\n        ]\n    }\n}"
              }
            }
          }
        }
      }
    },
    "/api/schedules": {
      "post": {
        "tags": ["Vehicle Service Reservation API"],
        "summary": "Schedule",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "serviceDate": "2023-04-01",
                  "quota": 10
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "219"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"db-xIrljWzZk+1W8tWIRoMLXG9MUMk\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 21 Jan 2026 18:22:57 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": true,\n    \"data\": {\n        \"id\": \"79d4414c-c758-408c-aa1a-16cec105d5dc\",\n        \"serviceDate\": \"2023-04-01T00:00:00.000Z\",\n        \"quota\": 10,\n        \"remainingQuota\": 10,\n        \"createdAt\": \"2026-01-21T18:22:57.000Z\",\n        \"updatedAt\": \"2026-01-21T18:22:57.000Z\"\n    }\n}"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "118"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"76-XY4kRQtB+z4ryfwgEQarRFM6X1I\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 21 Jan 2026 18:30:47 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": false,\n    \"message\": \"SCHEDULE_EXISTS\",\n    \"errors\": [\n        {\n            \"serviceDate\": \"schedule already exists for the given date.\"\n        }\n    ]\n}"
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "60"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3c-12I5LCQkEsA9Yuw3AEoXjRpkNes\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 21 Jan 2026 18:31:23 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": false,\n    \"message\": \"UNAUTHORIZED_ERROR\",\n    \"errors\": {}\n}"
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "87"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"57-Tfmj5+5HI0SSKArAVBCjfA7gp/E\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 21 Jan 2026 18:23:25 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "examples": {
                  "example-0": {
                    "summary": "Validation error",
                    "value": "{\n    \"success\": false,\n    \"message\": \"VALIDATION_ERROR\",\n    \"errors\": {\n        \"quota\": [\n            \"quota is required\"\n        ]\n    }\n}"
                  },
                  "example-1": {
                    "summary": "Invalid Request",
                    "value": "{\n    \"success\": false,\n    \"message\": \"VALIDATION_ERROR\",\n    \"errors\": {\n        \"\": [\n            \"value is required\"\n        ]\n    }\n}"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/schedules/bcc572fa-03b1-47e2-80b6-b1bc33d0a30a": {
      "put": {
        "tags": ["Vehicle Service Reservation API"],
        "summary": "Schedule",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "serviceDate": "2026-01-22",
                  "quota": 5
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "623"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"26f-yWsx3DuX8O/fG3nc1kNM08Wcy8Q\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 21 Jan 2026 20:35:44 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "example-0": {
                    "summary": "Success response",
                    "value": {
                      "success": true,
                      "data": {
                        "id": "4d209661-8448-4ea5-b0b0-583bf425ff46",
                        "serviceDate": "2026-01-19T00:00:00.000Z",
                        "quota": 5,
                        "remainingQuota": 4,
                        "createdAt": "2026-01-21T19:37:03.000Z",
                        "updatedAt": "2026-01-21T20:35:44.000Z",
                        "bookings": [
                          {
                            "id": "7720b9fe-6c28-49de-be82-11929df62d79",
                            "serviceScheduleId": "4d209661-8448-4ea5-b0b0-583bf425ff46",
                            "customerName": "Customer for Wed Jan 21 2026",
                            "phoneNo": "0812345610",
                            "vehicleType": "Car",
                            "licensePlate": "VEH-532",
                            "vehicleProblem": "Regular maintenance",
                            "scheduleTime": "09:00:00",
                            "status": "menunggu_konfirmasi",
                            "createdAt": "2026-01-21T19:37:03.000Z",
                            "updatedAt": "2026-01-21T19:37:03.000Z"
                          }
                        ]
                      }
                    }
                  },
                  "example-1": {
                    "summary": "Error update date scedule",
                    "value": {
                      "success": true,
                      "data": {
                        "id": "4d209661-8448-4ea5-b0b0-583bf425ff46",
                        "serviceDate": "2026-01-19T00:00:00.000Z",
                        "quota": 1,
                        "remainingQuota": 0,
                        "createdAt": "2026-01-21T19:37:03.000Z",
                        "updatedAt": "2026-01-21T20:36:10.000Z",
                        "bookings": [
                          {
                            "id": "7720b9fe-6c28-49de-be82-11929df62d79",
                            "serviceScheduleId": "4d209661-8448-4ea5-b0b0-583bf425ff46",
                            "customerName": "Customer for Wed Jan 21 2026",
                            "phoneNo": "0812345610",
                            "vehicleType": "Car",
                            "licensePlate": "VEH-532",
                            "vehicleProblem": "Regular maintenance",
                            "scheduleTime": "09:00:00",
                            "status": "menunggu_konfirmasi",
                            "createdAt": "2026-01-21T19:37:03.000Z",
                            "updatedAt": "2026-01-21T19:37:03.000Z"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "118"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"76-XY4kRQtB+z4ryfwgEQarRFM6X1I\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 21 Jan 2026 18:46:27 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": false,\n    \"message\": \"SCHEDULE_EXISTS\",\n    \"errors\": [\n        {\n            \"serviceDate\": \"schedule already exists for the given date.\"\n        }\n    ]\n}"
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "60"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3c-12I5LCQkEsA9Yuw3AEoXjRpkNes\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 21 Jan 2026 19:46:58 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": false,\n    \"message\": \"UNAUTHORIZED_ERROR\",\n    \"errors\": {}\n}"
              }
            }
          }
        }
      }
    },
    "/api/bookings": {
      "post": {
        "tags": ["Vehicle Service Reservation API"],
        "summary": "Error service schedule not found",
        "description": "Not found if the serviceDate in the Service Schedule is not H+1 or the remaining quota is insufficient.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "serviceScheduleId": "e4423e11-c89b-4d94-ad10-e0dd0c6a88d2",
                  "customerName": "test",
                  "phoneNo": "0987654321",
                  "vehicleType": "Avanza",
                  "licensePlate": "AB 1234 Test",
                  "vehicleProblem": "Rusak parah di bagian permesinan, dan kampas rem kadang bunyi",
                  "scheduleTime": "08:00"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "653"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"28d-CWpKeJ9MxAEFsbDSeqygLg7bht8\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 22 Jan 2026 05:19:39 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": true,\n    \"data\": {\n        \"id\": \"285a4bbd-b9d0-4201-8da3-2e020d0f5c98\",\n        \"serviceScheduleId\": \"e4423e11-c89b-4d94-ad10-e0dd0c6a88d2\",\n        \"customerName\": \"test\",\n        \"phoneNo\": \"0987654321\",\n        \"vehicleType\": \"Avanza\",\n        \"licensePlate\": \"AB 1234 Test\",\n        \"vehicleProblem\": \"Rusak parah di bagian permesinan, dan kampas rem kadang bunyi\",\n        \"scheduleTime\": \"08:00\",\n        \"status\": \"menunggu_konfirmasi\",\n        \"createdAt\": \"2026-01-22T05:19:39.000Z\",\n        \"updatedAt\": \"2026-01-22T05:19:39.000Z\",\n        \"serviceSchedule\": {\n            \"id\": \"e4423e11-c89b-4d94-ad10-e0dd0c6a88d2\",\n            \"serviceDate\": \"2026-01-23T00:00:00.000Z\",\n            \"quota\": 15,\n            \"remainingQuota\": 10,\n            \"createdAt\": \"2026-01-22T05:11:03.000Z\",\n            \"updatedAt\": \"2026-01-22T05:19:39.000Z\"\n        }\n    }\n}"
              }
            }
          },
          "404": {
            "description": "Not Found",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "101"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"65-DV4miO8BlZmTXrOi19Og9WKnmrI\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 22 Jan 2026 05:06:13 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": false,\n    \"message\": \"NOT_FOUND_ERROR\",\n    \"errors\": [\n        {\n            \"resources\": [\n                \"service schedule not found\"\n            ]\n        }\n    ]\n}"
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "269"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"10d-m+EDFfEoZ/GxNU+SW5bhPM/IzQ4\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 22 Jan 2026 05:20:45 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": false,\n    \"message\": \"VALIDATION_ERROR\",\n    \"errors\": {\n        \"phoneNo\": [\n            \"phoneNo is required\"\n        ],\n        \"vehicleType\": [\n            \"vehicleType is required\"\n        ],\n        \"licensePlate\": [\n            \"licensePlate is required\"\n        ],\n        \"vehicleProblem\": [\n            \"vehicleProblem is required\"\n        ],\n        \"scheduleTime\": [\n            \"scheduleTime is required\"\n        ]\n    }\n}"
              }
            }
          }
        }
      }
    },
    "/api/bookings/1110c817-ffdb-431f-9471-b061f9b30fd5": {
      "patch": {
        "tags": ["Vehicle Service Reservation API"],
        "summary": "Bookings",
        "requestBody": {
          "content": {
            "*/*": {
              "schema": {
                "type": "string",
                "example": "\"{\\n    \\\"status\\\": \\\"menunggu_konfirmasi\\\"\\n}\""
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "627"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"273-E6quMv7cuVqDXF/WvUw7txNLyhQ\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 22 Jan 2026 05:54:58 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": true,\n    \"data\": {\n        \"id\": \"1110c817-ffdb-431f-9471-b061f9b30fd5\",\n        \"serviceScheduleId\": \"087eace8-0b41-4042-b558-17f39177171b\",\n        \"customerName\": \"Customer for Wed Jan 28 2026\",\n        \"phoneNo\": \"0812345897\",\n        \"vehicleType\": \"Car\",\n        \"licensePlate\": \"VEH-638\",\n        \"vehicleProblem\": \"Regular maintenance\",\n        \"scheduleTime\": \"09:00:00\",\n        \"status\": \"konfirmasi_datang\",\n        \"createdAt\": \"2026-01-22T05:11:03.000Z\",\n        \"updatedAt\": \"2026-01-22T05:54:59.000Z\",\n        \"serviceSchedule\": {\n            \"id\": \"087eace8-0b41-4042-b558-17f39177171b\",\n            \"serviceDate\": \"2026-01-28T00:00:00.000Z\",\n            \"quota\": 10,\n            \"remainingQuota\": 9,\n            \"createdAt\": \"2026-01-22T05:11:03.000Z\",\n            \"updatedAt\": \"2026-01-22T05:54:59.000Z\"\n        }\n    }\n}"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "104"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"68-1cKjAaDjbZOF+noBj94H5VZA3ZE\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 22 Jan 2026 05:57:42 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": false,\n    \"message\": \"VALIDATION_ERROR\",\n    \"errors\": [\n        {\n            \"resources\": [\n                \"no remaining quota available\"\n            ]\n        }\n    ]\n}"
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "60"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3c-12I5LCQkEsA9Yuw3AEoXjRpkNes\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 22 Jan 2026 05:49:18 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": false,\n    \"message\": \"UNAUTHORIZED_ERROR\",\n    \"errors\": {}\n}"
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "122"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"7a-EC+UvvGHKcoSr9mQGXpqX/Hrj+0\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 22 Jan 2026 05:55:26 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "{\n    \"success\": false,\n    \"message\": \"VALIDATION_ERROR\",\n    \"errors\": {\n        \"id\": [\n            \"id must be a valid GUID\"\n        ],\n        \"status\": [\n            \"status is required\"\n        ]\n    }\n}"
              }
            }
          }
        }
      }
    }
  }
}
